// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ3cq_IgyjJ1QSYX2Nl-4u8SvoEru5Vsc',
    appId: '1:234675598935:web:d71f47764e03134f019512',
    messagingSenderId: '234675598935',
    projectId: 'komunity-76c8c',
    authDomain: 'komunity-76c8c.firebaseapp.com',
    storageBucket: 'komunity-76c8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhx9VFqQnMHiVhFNfT9yFEoEv8DwoxNCM',
    appId: '1:234675598935:android:2add2b9f2a787242019512',
    messagingSenderId: '234675598935',
    projectId: 'komunity-76c8c',
    storageBucket: 'komunity-76c8c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ3cq_IgyjJ1QSYX2Nl-4u8SvoEru5Vsc',
    appId: '1:234675598935:web:d9462baa98a854b2019512',
    messagingSenderId: '234675598935',
    projectId: 'komunity-76c8c',
    authDomain: 'komunity-76c8c.firebaseapp.com',
    storageBucket: 'komunity-76c8c.firebasestorage.app',
  );
}
